name: Executable Creation
run-name: "TRCLI Executable - Deploy to ${{ github.event.inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - staging
          - production

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        arch: [amd64, arm64]
        include:
          - os: windows-latest
            name: windows
          - os: ubuntu-20.04
            name: linux
          - os: macos-latest
            name: macos


    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install pyinstaller

      - name: Create Executable Using Pyinstaller
        run: |
          ls
          pwd
          pyinstaller main.spec
          ls dist
      
      - name: Print Executable Version
        run: |
           if [ "${{ matrix.name }}" = "windows" ]; then
              ./dist/trcli-exe.exe --help
           else
              ./dist/trcli-exe --help
           fi
        shell: bash

      # Set environment variables
      - name: Set environment variables
        run: |
          echo "Environment: ${{ github.event.inputs.environment }} "
          echo "Github Workspace Folder: ${{ github.workspace }}"

          echo "AWS_DEFAULT_OUTPUT=json" >> $GITHUB_ENV
         
          if [[ ${{ github.event.inputs.environment }} == production ]]; then
            echo "AWS_ROLE_ARN=${{ secrets.PROD_AWS_GITHUB_OIDC_ROLE_ARN }}" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.PROD_GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "WORKLOAD_ID=${{ secrets.PROD_GCP_WORKLOAD_ID }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ secrets.PROD_GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
            echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_URL=us-east4-docker.pkg.dev" >> $GITHUB_ENV
            echo "EKS_COMMON_BUCKET=eks-common-prod-bucket" >> $GITHUB_ENV
          else
            echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_URL=us-east4-docker.pkg.dev" >> $GITHUB_ENV
            echo "AWS_ROLE_ARN=${{ secrets.STAGE_AWS_GITHUB_OIDC_ROLE_ARN }}" >> $GITHUB_ENV
            echo "PROJECT_ID=${{ secrets.STAGE_GCP_PROJECT_ID }}" >> $GITHUB_ENV
            echo "WORKLOAD_ID=${{ secrets.STAGE_GCP_WORKLOAD_ID }}" >> $GITHUB_ENV
            echo "SERVICE_ACCOUNT=${{ secrets.STAGE_GCP_SERVICE_ACCOUNT }}" >> $GITHUB_ENV
            echo "EKS_COMMON_BUCKET=eks-common-bucket" >> $GITHUB_ENV
          fi


      # Set up environment variables for the cloud provider
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Upload Executable to S3
        run:
          aws s3 cp --recursive dist/ s3://$EKS_COMMON_BUCKET/trcli-executable/${{ matrix.name }}-${{ matrix.arch }}/
        shell: bash
