name: Executable Creation
run-name: "TRCLI Executable - Deploy to ${{ github.event.inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        include:
          - os: windows-latest
            name: windows
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: macos


    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install pyinstaller

      - name: Create Executable Using Pyinstaller
        run: |
          ls
          pwd
          pyinstaller main.spec
          ls dist

      - name: Set up environment variables
        run: |
            echo "AWS_DEFAULT_OUTPUT=json" >> $GITHUB_ENV
  
            if [ "${{ github.event.inputs.environment }}" = "production" ]; then
              echo "AWS_ACCESS_KEY_ID=${{ secrets.APP_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
  
              if [ "${{ github.event.inputs.region }}" = "EU" ]; then
                echo "AWS_DEFAULT_REGION=eu-west-1" >> $GITHUB_ENV
                echo "EKS_COMMON_BUCKET=eks-common-prod-bucket-eu" >> $GITHUB_ENV
              else
                echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
                echo "EKS_COMMON_BUCKET=eks-common-prod-bucket-eu" >> $GITHUB_ENV
              fi
  
            else
              echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
              echo "AWS_ACCESS_KEY_ID=${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
              echo "EKS_COMMON_BUCKET=eks-common-bucket" >> $GITHUB_ENV
            fi

        shell: bash
    
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_DEFAULT_REGION }}
  
      - name: Upload Executable to S3
        run:
          aws s3 cp --recursive dist/ s3://$EKS_COMMON_BUCKET/trcli-executable/${{ matrix.name }}-${{ matrix.os }}/
        shell: bash
