name: Executable Creation
run-name: "TRCLI Executable - Deploy to ${{ github.event.inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install pyinstaller

      - name: Create Executable
        run:  |
          pyinstaller --onefile main.spec


